### ISSUE TITLE
设置拖动图片后，拖动图片会放大，没有放大和不放大的属性

### ISSUE THREAD

**Issue by imhappyok** [jenly1314/ArcSeekBar#11]

**Comment by jenly1314** [comment]
`Thumb`相关的属性就那么几个，你看下说明就应该知道了。

**Comment by imhappyok** [comment]
确实只有几个属性，但是没找到我想要的这个

**Comment by imhappyok** [comment]
<html>
<body>

arcThumbStrokeWidth | dimension | 8dp | 拖动按钮描边宽度
-- | -- | -- | --
arcThumbColor | color | #FFE8D30F | 拖动按钮颜色
arcThumbRadius | dimension | 10dp | 拖动按钮半径
arcThumbRadiusEnlarges | dimension | 8dp | 触摸时按钮半径放大量
arcShowThumb | boolean | true | 是否显示拖动按钮
arcThumbDrawable | reference |   | 拖动按钮图片（arcThumbDrawable的优先级高于arcThumbColor）
arcAllowableOffsets | dimension | 10dp | 触摸时可偏移距离：偏移量越大，触摸精度越小


</body>
</html>
