### ISSUE TITLE
拖动条默认是渐变色，但是没有设置渐变色的属性，只能设置一种颜色

### ISSUE THREAD

**Issue by imhappyok** [jenly1314/ArcSeekBar#12]

**Comment by jenly1314** [comment]
[setProgressColor](https://github.com/jenly1314/ArcSeekBar/blob/master/arcseekbar/src/main/java/com/king/view/arcseekbar/ArcSeekBar.java#L884)

**Comment by imhappyok** [comment]
ok，原来可以传多参数
