### ISSUE TITLE
可以设置最小值吗？

### ISSUE THREAD

**Issue by imhappyok** [jenly1314/ArcSeekBar#13]
现在需求滑动范围是20-50，库默认是0-100,可以修改最大为50，但是没看到可以设置最小值

**Comment by jenly1314** [comment]
> 现在需求滑动范围是20-50，库默认是0-100,可以修改最大为50，但是没看到可以设置最小值

这个我有空的时候加一下，你可以先自己简单换算下；
`max = rawMax - rawMin`
`rawProgress = progress + rawMin`

**Comment by imhappyok** [comment]
我怎么改变步进，距离为我想要20到50，但是每次滑动是以0.5为进度的，我看当前好像是1



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月16日 16:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jenly1314/ArcSeekBar] 可以设置最小值吗？ (Issue #13) |

现在需求滑动范围是20-50，库默认是0-100,可以修改最大为50，但是没看到可以设置最小值

这个我有空的时候加一下，你可以先自己简单换算下；
max = rawMax - rawMin
rawProgress = progress + rawMin

**Comment by jenly1314** [comment]
> `max = rawMax - rawMin`
> `rawProgress = progress + rawMin`



> 我怎么改变步进，距离为我想要20到50，但是每次滑动是以0.5为进度的，我看当前好像是1
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年10月16日 16:55 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [jenly1314/ArcSeekBar] 可以设置最小值吗？ (Issue #13) | 现在需求滑动范围是20-50，库默认是0-100,可以修改最大为50，但是没看到可以设置最小值 这个我有空的时候加一下，你可以先自己简单换算下； max = rawMax - rawMin rawProgress = progress + rawMin — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

还是一样，假设步进为：step，代入进行换算；

`max = (rawMax - rawMin) / step`
`rawProgress = progress * step + rawMin`

**Comment by imhappyok** [comment]
还有个问题，当我设置最小值0，最大值3，发现拉动不了，最大值是4就可以，不知道是不是有什么限制住了

**Comment by jenly1314** [comment]
> 还有个问题，当我设置最小值0，最大值3，发现拉动不了，最大值是4就可以，不知道是不是有什么限制住了

[限制原因：防止滑动突变](https://github.com/jenly1314/ArcSeekBar/blob/master/arcseekbar/src/main/java/com/king/view/arcseekbar/ArcSeekBar.java#L716)

**Comment by imhappyok** [comment]
可以添加属性，让我可以设置去掉这个限制吗，不然有可能出现这种情况，别人就提bug了

**Comment by jenly1314** [comment]
> 可以添加属性，让我可以设置去掉这个限制吗，不然有可能出现这种情况，别人就提bug了

加限制的初衷就是防止滑动突变，只是有这个限制可能不满足你的需求场景；等有空时再改，急的话你也可以自己改。

**Comment by imhappyok** [comment]
好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月17日 17:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [jenly1314/ArcSeekBar] 可以设置最小值吗？ (Issue #13) |

可以添加属性，让我可以设置去掉这个限制吗，不然有可能出现这种情况，别人就提bug了

加限制的初衷就是防止滑动突变，只是有这个限制可能不满足你的需求场景；等有空时再改，急的话你也可以自己改。
