### ISSUE TITLE
设置渐变色无效

### ISSUE THREAD

**Issue by simplettton** [jenly1314/ArcSeekBar#3]
arcSeekBar.setProgressColor(colors)函数设置渐变色无效

**Comment by jenly1314** [comment]
设置渐变色需在 **ArcSeekBar** 执行了 **onMeasure**  方法之后再调用 **arcSeekBar.setProgressColor(colors);** 之后才有效果，即 **ArcSeekBar** 需测量出半径，才能使用默认渐变的着色样式。或者你也可以自己设置着色器 **arcSeekBar.setShader(shader);** 来是实现想要的渐变样式

**Comment by simplettton** [comment]
好的！感谢感谢 *⸜( •ᴗ• )⸝*------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Jenly&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月11日(星期三) 下午3:37
收件人:&nbsp;&quot;jenly1314/ArcSeekBar&quot;<ArcSeekBar@noreply.github.com&gt;;
抄送:&nbsp;&quot;simplettton&quot;<515315183@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jenly1314/ArcSeekBar] 设置渐变色无效 (#3)
