### ISSUE TITLE
渐变色的设置

### ISSUE THREAD

**Issue by qq171161636** [jenly1314/ArcSeekBar#4]
我是这样设置的渐变色
 int[] mShaderColors = new int[]{0xFFFF5A5D,0xFFFE733E,0xFFFE8227,0xFFFF5A5D};
 mCirProgeress.setProgressColor(mShaderColors);
 mCirProgeress.showAnimation(88,2000);
但是一直无效，然后去你的源码里面改成如上颜色值就才有作用。
麻烦指点一下怎么设置渐变。

**Comment by jenly1314** [comment]
#3
