### ISSUE TITLE
Shader SweepGradient好像有点问题

### ISSUE THREAD

**Issue by Deaful** [jenly1314/ArcSeekBar#9]
进度圈渐变效果有点奇怪：设置了白色到橙色的渐变，270-360度区间显示橙色，然后从360度开始才是渐变色。

**Comment by xiaoe1314** [comment]
我也遇到一样的问题，如果设置其他的渐变颜色，开始角度会从360度开始

**Comment by xiaoe1314** [comment]
我这样改后，成功了

/**
     * 设置进度颜色（通过着色器实现渐变色）
     * @param colors
     */
    public void setProgressColor(int... colors){

        Logger.d("logger===rgb===isMeasureCircle==============" + isMeasureCircle);
//        if(isMeasureCircle){
//            Shader shader = new SweepGradient(mCircleCenterX, mCircleCenterX, colors,null);
//            setShader(shader);
//        }else{
//            mShaderColors = colors;
//            isShader = true;
//        }

        mShaderColors = colors;
        invalidate();
    }

**Comment by xiaoe1314** [comment]
我修改成这样，能解决问题

/**
     * 设置进度颜色（通过着色器实现渐变色）
     * @param colors
     */
    public void setProgressColor(int... colors){
        if(isMeasureCircle){
            Shader shader = new SweepGradient(mCircleCenterX,mCircleCenterX,colors,null);
            Matrix matrix = new Matrix();
            matrix.setRotate(-90, mCircleCenterX,mCircleCenterX);
            shader.setLocalMatrix(matrix);
            setShader(shader);
        }else{
            mShaderColors = colors;
            isShader = true;
        }
    }

**Comment by jenly1314** [comment]
> 我修改成这样，能解决问题
> 
> /** * 设置进度颜色（通过着色器实现渐变色） * @param colors */ public void setProgressColor(int... colors){ if(isMeasureCircle){ Shader shader = new SweepGradient(mCircleCenterX,mCircleCenterX,colors,null); Matrix matrix = new Matrix(); matrix.setRotate(-90, mCircleCenterX,mCircleCenterX); shader.setLocalMatrix(matrix); setShader(shader); }else{ mShaderColors = colors; isShader = true; } }

```setProgressColor(int... colors)```只是一个传入多颜色的方式（内部实例化一个默认的着色器）来实现渐变；如果默认的着色器的渐变效果满足不了你的需求，你完全可以要自定义着色器（包括渐变色的角度区间）来实现你想要的渐变效果，直接使用```setShader(Shader shader)``` 即可。
